images:
  repository: "docker.io/jessynt/counter"
  tag: v0.0.1
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  httpPort: 80
ingress:
  enabled: false
#  annotations:
#    kubernetes.io/ingress.class: nginx
#  hosts:
#  - counter.demo.io