apiVersion: v1
kind: Service
metadata:
  name: {{ template "counter.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  selector:
    app: {{ template "counter.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.httpPort }}
    targetPort: 8080